version: "3"

services:
  flexiflex-front-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
        - default
    labels:
      - "traefik.frontend.rule=Host:flexiflex.tk"
      - "traefik.port=8080"
networks:  
  default:
    external:
      name: traefik_default
