version: "3"

services:
  flexiflex-front-server:
    ports:
      - 9091:8080
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    labels:
      traefik.backend: "flexiflex-frontend"
      traefik.frontend.rule: "Host:flexiflex.tk"
      traefik.enable: "true"
